title: "nO nAME"
email: contact@aymonin.me
baseurl: "" #The subpath of your site, e.g. /blog/
url : "" #TODO

include: []
exclude: ["README.md"]
encoding: "utf-8"
permalink: /:title/

timezone: Europe/Paris
paginate: 5
paginate_path: /page/:num
